- name: Create Application User
  user:
    name: "{{ app_user }}"
    home: "{{ app_home }}"
    system: yes
    shell: /bin/bash

- name: Create Configuration Directory
  file:
    path: "{{ app_configuration_directory }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0775

- name: Create Log Directory
  file:
    path: "{{ app_log_directory }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0775

- name: Create Data Directory
  file:
    path: "{{ app_data_directory }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0775

- name: Create Backup Directory
  file:
    path: "{{ app_backup_directory }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0775

- name: Change Repository Permissions
  file:
    path: "/var/git/{{ app_user }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    recurse: yes
    mode: 0775
  ignore_errors: true

- name: "Symlink {{ app_user }} Repository"
  become: yes
  become_user: "{{ app_user }}"
  file:
    src: "/var/git/{{ app_user }}"
    dest: "{{ app_repository }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    state: link
  ignore_errors: true

- name: "Install Wheels in Virtualenv"
  become: yes
  become_user: "{{ app_user }}"
  pip:
    name: "wheel"
    virtualenv: "{{ app_env }}"

- name: "Install Requirements Inside Virtualenv"
  become: yes
  become_user: "{{ app_user }}"
  pip:
    requirements: "{{ app_requirements_path }}"
    virtualenv: "{{ app_env }}"

- name:  "Create Cron Job {{ app_user }}"
  cron: 
    name: "{{ app_user }} deploy updates with Cron Job"
    user: "root"
    hour: "*"
    minute: "0"
    job: "cd /opt/{{ app_user }}/{{ app_user }} && git pull"
    cron_file: "{{ app_user }}_update"
